### ISSUE TITLE
RNN models converted by keras-onnx failed to run with onnt-tf backend

### ISSUE THREAD

**Issue by fjfjfan** [onnx/keras-onnx#128]
Dear admin,
As describe in https://github.com/onnx/onnx-tensorflow/issues/441,  the RNN models converted by keras-onnx(code from master branch) failed to run with onnt-tf backend, while the old models converted by keras-onnx some days ago could work with onnx-tf. 

Here is the response from onnx-tf:
`The problem seems coming from Reshape, taking inputs of data 'rnn_y_permuted': <tf.Tensor 'Transpose1:0' shape=(?, 6, 1, 128) dtype=float32> and 'shape_tensor': <tf.Tensor 'Const_3:0' shape=(3,) dtype=int64> with [-1, 6, 128] and producing output 'simple_rnn_1_transpose_1_0': <tf.Tensor 'Reshape:0' shape=(?, ?, ?) dtype=float32>. This data will cause tf.nn.dynamic_rnn to fail. I think the solution might be in the keras converter.`

Meanwhile, sonu1-p thought it might caused by " the keras-onnx converter is that it does not add the initializers as "inputs" in the generated onnx model".

Could you please help have a look? Thanks a lot!

**Comment by wenbingl** [comment]
@fjfjfan , It's intentional and it actually was clarified in this commit 
https://github.com/onnx/onnx/commit/dc75285d4a1cff9618400164dfdb26c5a1bab70a#diff-c47706bf7deab021b45fdc8f11138814  

". Names of constants that are not meant to overridden by the caller should appear only in the initializer list and not in the graph input list."

All converters in the onnxmltools collection are following this guideline.
