### ISSUE TITLE
RuntimeError: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:Pad : Node (Pad) has input size 3 not in range [min=1, max=1].

### ISSUE THREAD

**Issue by Royzon** [onnx/keras-onnx#324]
when I run the code below in your README, I got this problem, I want to know how to solve it?

import numpy as np
from keras.preprocessing import image
from keras.applications.resnet50 import preprocess_input
import keras2onnx
import onnxruntime

# image preprocessing
img_path = 'street.jpg'   # make sure the image is in img_path
img_size = 224
img = image.load_img(img_path, target_size=(img_size, img_size))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

# load keras model
from keras.applications.resnet50 import ResNet50
model = ResNet50(include_top=True, weights='imagenet')

# convert to onnx model
onnx_model = keras2onnx.convert_keras(model, model.name)

# runtime prediction
content = onnx_model.SerializeToString()
sess = onnxruntime.InferenceSession(content)
x = x if isinstance(x, list) else [x]
feed = dict([(input.name, x[n]) for n, input in enumerate(sess.get_inputs())])
pred_onnx = sess.run(None, feed)

**Comment by jiafatom** [comment]
Resnet50 is in our nightly build [here](https://github.com/onnx/keras-onnx/blob/5964f90c22b80a0df8d35524df477855c6cd5aa2/applications/nightly_build/test_keras_applications.py#L65-L69) and runs smoothly. Seems that you have converted an onnx model of opset 11, but onnxruntime treats it as opset 10 (Pad schema changes since opset 11). 
(1) Which version of keras2onnx, onnxruntime, onnx you are using?
(2) Can you try `keras2onnx.convert_keras(model, model.name, target_opset=10)` to see if can work?

**Comment by Royzon** [comment]
I meet the same problem of your nightly build Resnet50, I tried the second method and the problem was solved.
my config information:
keras=2.3.1
kears2onnx=1.6.0
onnxruntime=0.5.0
onnx=1.6.0
onnxconverter-common=1.6.1

**Comment by jiafatom** [comment]
@Royzon The issue is because onnxruntime 0.5.0 only supports until opset 10, so it cannot deal with opset 11 models. Try using onnxruntime 1.0.0+ then you don't need method (2).
