### ISSUE TITLE
Do we know layer/weight/input/output correspondance between keras model and the onnx model

### ISSUE THREAD

**Issue by atemysemicolon** [onnx/keras-onnx#356]
I am currently trying to convert a keras model to an onnx model. Inferring on the onnx model seems to be quite different (visually) than the keras model.

Is there some kind of layer correspondence, so I can compare keras outputs after that layer with onnx outputs after that layer?

**Comment by jiafatom** [comment]
Usually the keras operator name is part of the names of corresponding onnx operators. You mentioned inferring is different? Does it mean the result mismatch?

**Comment by hoaquocphan** [comment]
Hi @jiafatom 
I have the same concern with the author.

the result When I importing  the keras .h5 file by python and onnx file by C are different.
so is it different or I have some mistake in importing?

**Comment by jiafatom** [comment]
Generally speaking, if the difference is less than 1% or 0.1%, we treat it the same because this is numerical difference. If the difference is very large, please share the model.

**Comment by hoaquocphan** [comment]
Hi @jiafatom  

this is not my mean, so I will re-explain my question.

I'm Porting [Yolov3](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3) 

1/ run python [yolo3](https://github.com/experiencor/keras-yolo3) script

script (pre-processing) + Model.h5 file -> data1
data1 + script (post-processing)  -> detected image

2/ create C [yolo3](https://github.com/hoaquocphan/Tiny_Yolo_v3) 

my code C (pre-processing) + Model.onnx -> data2
data2 + my code C (post-processing) -> detected image (error)

the difference here is **data1** and **data2**
currently, I don't know the difference because of mistake in my code or the difference of .h5 file and .onnx file?

so if it because of my code, could you check my code(pre-processing step) and give me the comment about mistake?

Thanks

**Comment by jiafatom** [comment]
Now your issue is mixed, it is better to separate each component to debug. We have unit test for yolov3 in onnx keras2onnx repo. And we have yolov3 in our model zoo. These are correct models. You can try your preprocessing to see if it works for you.

**Comment by hoaquocphan** [comment]
Hi @jiafatom 

of course, I download the Model.onnx  from onnx model zoo so don't need to test the model.onnx.
what I concern here is as below: 

the [yolov3](https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3) on model zoo was convert from [keras-yolo3](https://github.com/qqwweee/keras-yolo3)
when check the [python code](https://github.com/qqwweee/keras-yolo3/blob/e6598d13c703029b2686bc2eb8d5c09badf42992/yolo.py),  I see that the use some functions (K.concatenate; K.constant; K.gather; K.ones_like) with the model.h5.
So my question is:
does these functions + model.h5 was convert to Model.onnx or they just convert the model.h5  file only?
if the Model.onnx have no functions like this, how to use these function in C code.

Thanks

**Comment by jiafatom** [comment]
Yes, the functions and model.h5 is converted to model.onnx, and the onnx model should be correct.
you mentioned how to use these function in C code, this is an onnxruntime issue, so onnxruntime is the right place to raise issue.

**Comment by hoaquocphan** [comment]
Hi @jiafatom 

Thanks for your reply
