### ISSUE TITLE
tensorflow 2.x.x support

### ISSUE THREAD

**Issue by mxdilln** [onnx/keras-onnx#392]
Is there an estimate of when tensorflow 2 will be supported by the package? 

When trying to run 
```
keras2onnx.convert_keras()
```
with `keras2onnx==1.6.0` and `tensorflow==2.1.0` on a tf.keras model, I get the following error:

```
RuntimeError: tf2onnx loading failed with the tensorflow package!
```

**Comment by wenbingl** [comment]
Can you install the package from the source code?
The pip package release was postponed for some reason.

**Comment by mxdilln** [comment]
Thanks, that has removed that particular error, but replaced it with an assertion error:

```
The tf.op node lstm/StatefulPartitionedCall/args_5 of type Placeholder cannot be converted
There is an error(<class 'AssertionError'>) happened during optimizing on the converted model!

Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/keras2onnx/topology.py", line 315, in convert_topology
    target_opset=container.target_opset)
  File "/venv/lib/python3.7/site-packages/onnxconverter_common/optimizer.py", line 1304, in optimize_onnx_graph
    initializers)
  File "/venv/lib/python3.7/site-packages/onnxconverter_common/optimizer.py", line 268, in build_from_onnx
    assert var_ == '' or var_ in inputs
AssertionError
```

I am not using `tf.placeholders` in my code anywhere, so not sure what this is referring to. The model definition is:

```
    def define_model(self):
        """Define model architecture and compile model."""
        self.model = tf.keras.models.Sequential([
            tf.keras.layers.LSTM(128, input_shape=(None,28)),
            tf.keras.layers.BatchNormalization(),
            tf.keras.layers.Dense(10, activation="softmax"),
        ])
```

**Comment by bigcola317** [comment]
I have the same issue while trying to convert the https://github.com/philipperemy/keras-tcn model. 

The placeholder appears as an input to a ReadVariableOp and is supposed to be a trained bias parameter.

I'm calling `keras2onnx.convert_keras()` right after training.
I'm using keras2onnx 1.6.5 and tensorflow 2.1.0.

Is there any insight since the last activity on this issue?

**Comment by wenbingl** [comment]
stay tune and I will have a fix for that this week.

**Comment by bigcola317** [comment]
Perfect thanks! I can share my code if you need it to reproduce the error.

**Comment by wenbingl** [comment]
It turns out even tensorflow.tflite can't convert this kind of model to tflite model.
The issue basically is that the public tf API cannot extract the graph from the Keras model if the model has some kinds of layer. But it works if the model code was written in a subclassing way.
Let me see if there is any good way to solve this issue.

**Comment by bigcola317** [comment]
Actually I managed to convert the model to TF Lite. 
Are you referring to the BatchToSpaceND layer? I solved that by merging a couple of PRs to Tensorflow's master branch, specifically 27867 and 28179.
I believe the TCN's custom layers are already implemented as subclasses of the Layer class, if that is what you mean.

**Comment by wenbingl** [comment]
Some Recent PRs has fixed the issues in these models and I verified it on the model example shared  by @mxdilln and on keras-tcn model/tf.keras shared by @bigcola317 .

Can you guys have a try?

**Comment by bigcola317** [comment]
I can confirm that it works for the keras-tcn model.
Thanks a lot!
