### ISSUE TITLE
the onnx_model can not use in openvino

### ISSUE THREAD

**Issue by Martin0Li** [onnx/keras-onnx#426]
I got a squeezenet.onnx from openvino model zoo. And I convert the model to keras from onnx2keras[https://github.com/nerox8664/onnx2keras](url). So I want to convert this keras model to onnx. But it is different between  convert before and after.

**Comment by jiafatom** [comment]
Can you share the model please?

**Comment by Martin0Li** [comment]
Thank you so much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"David Fan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月7日(星期二) 凌晨3:27
收件人:&nbsp;"onnx/keras-onnx"<keras-onnx@noreply.github.com&gt;;
抄送:&nbsp;"MT"<785415704@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [onnx/keras-onnx] the onnx_model can not use in openvino (#426)





 
Can you share the model please?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

squeezenet1.1.onnx (4.73M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=71383735b36682c72e46e71b45390417520a07020001575d1b0d01505b14020e545a1a0c540b0f15570d030353000e5a06085556632b364b474d5250195c585d420919044d5658564e380a&t=exs_ftn_download&code=6875c968

**Comment by jiafatom** [comment]
This issue contains two steps: (1) onnx->keras model using other repo (2) keras->onnx model using keras2onnx.
It is possible that the final onnx model is different, because there is no guarantee that the two steps keep the model the same. As long as the inference result is the same, you don't need worry about it. If the inference is different, then we need first understand if (1) or (2) causes the difference. And only (2) is in the scope of keras2onnx.
