### ISSUE TITLE
channel_first_inputs does not work with LSTM

### ISSUE THREAD

**Issue by AlexRibard** [onnx/keras-onnx#509]
Hello,
I am trying to convert the following .h5 model to .onnx.
However when trying to convert to onnx, even when using channel_first_inputs, keras2onnx adds a `Transpose` in front of the `LSTM` layer.
It would seem that channel_first_inputs doesn't work with the LSTM layer...

Thanks!

Model:
[lstm_model.zip](https://github.com/onnx/keras-onnx/files/4712183/lstm_model.zip)
Repro code:
```
import keras2onnx
onnx_model = keras2onnx.convert_keras(model2, name="lstm", target_opset=9, channel_first_inputs='lstm')
keras2onnx.save_model(onnx_model, 'lstm.onnx')
```

**Comment by jiafatom** [comment]
Just checked this issue, I need 
```python
    from tensorflow.keras.models import load_model
    from tensorflow.keras.utils import CustomObjectScope
    from tensorflow.keras.initializers import glorot_uniform

    with CustomObjectScope({'GlorotUniform': glorot_uniform()}):
        model = load_model('lstm_model.h5')
        onnx_model = keras2onnx.convert_keras(model, name="lstm", target_opset=9, channel_first_inputs='lstm')
```
to reproduce.

Anyway the model converts correctly. Yes, the converter need add a `Transpose` before `LSTM`. That is not the converter problem, it is because the input of `LSTM` in onnx spec is `[seq_length, batch_size, input_size]`. When we say `channel_first_inputs`, it usually mean `batch_size` is dim 0. But here for `LSTM`, `batch_size` is dim 1, so we have to add `Transpose` during conversion.

In sum, the reason is the input shape of `LSTM` in onnx spec puts `batch_size` to dim 1. So `LSTM` conversion will have a `Transpose`.

**Comment by AlexRibard** [comment]
Thanks!

**Comment by smasish** [comment]
I tried using the above code but does not convert lstm h5 model to onnx. It shows AttributeError: 'str' object has no attribute '_is_graph_network'
My lstm model had 9 features including target class and following code is used.
onnx_model = keras2onnx.convert_keras(LSTM.h5, name="lstm", target_opset=8, channel_first_inputs='lstm')
keras2onnx.save_model(onnx_model, 'lstm.onnx')

Any suggestions how to convert this model to onnx format?
