### ISSUE TITLE
Failure in converting model with mask_zero=True in embedding layer

### ISSUE THREAD

**Issue by sonu1-p** [onnx/keras-onnx#90]
I wanted to convert a keras model that is using an embedding layer with mask_zero=True.
But it fails as it seems keras2onnx does not support this usecase.

Here is the error I get -
  File "venv/lib/python3.6/site-packages/keras2onnx/ke2onnx/embedding.py", line 15, in convert_keras_embed
    raise NotImplementedError("Embedding layer mask_zero attribute cannot be converted")
NotImplementedError: Embedding layer mask_zero attribute cannot be converted

Is there a way we can get around supporting this? Any suggestions will be appreciated. Please feel free to close this if this is not the right place for this question.

**Comment by jiafatom** [comment]
@sonu1-p Unfortunately we do not support this mask_zero=True case. If mask_zero=True, what is the onnx model look like? How does the following layers handle mask? If the onnx node can have this function, we may probably convert it, otherwise it seems very hard. Maybe post this question to onnx to ask whether they defines this similar behavior?

**Comment by sonu1-p** [comment]
I needed the converted model for inference only and seems this masking is needed for training time only. So I just commented out the lines that threw error and successfully converted the model and verified that it produced same result as keras. So, my issue was solved.
Thanks for looking into this. You can resolve this.
